#############################################################
# 1. Model Define Configs
#############################################################

#############################################################
# 2. Optimizer & Train Configs
#############################################################

#############################################################
# 3. DataSet Config
#############################################################  
DatasetConfig:
  dataset: 'db1'
  batch_size: 128  
  num_workers: 6
  seq_lens: [20] # sample rate: 100Hz -> 1 dot: 10ms
  step: 1
  root_path: 'data/ninapro/db1_processed/'

#############################################################
# 4. Output Config
#############################################################  

