#############################################################
# 1. Model Define Configs
#############################################################

#############################################################
# 2. Optimizer & Train Configs
#############################################################

#############################################################
# 3. DataSet Config
#############################################################  
DatasetConfig:
  dataset: 'db2'
  batch_size: 32  
  num_workers: 6
  seq_lens: [200] # sample rate: 2000Hz -> 1 dot: 0.5ms
  step: 50
  root_path: 'data/ninapro/db2_processed/'

#############################################################
# 4. Output Config
#############################################################  

